export const config = {
  IA_URL: process.env.NEXT_PUBLIC_IA_URL,
  EMAIL_HOST: process.env.NEXT_PUBLIC_EMAIL_HOST,
  EMAIL_USER: process.env.NEXT_PUBLIC_EMAIL_USER,
  EMAIL_PASSWORD: process.env.NEXT_PUBLIC_EMAIL_PASSWORD,
  EMAIL_SMTP_PORT: process.env.NEXT_PUBLIC_EMAIL_SMTP_PORT,
  EMAIL_IMAP_PORT: process.env.NEXT_PUBLIC_EMAIL_IMAP_PORT,
  EMAIL_POP3_PORT: process.env.NEXT_PUBLIC_EMAIL_POP3_PORT,
};
