networks:
  gcp_network:
    name: ${DOCKER_NETWORK}
    driver: bridge
    external: true

services:
  app.fe.argus:
    container_name: app.fe.argus
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - APP_STAGE=${STAGE}
    environment:
      STAGE: ${STAGE}
    ports:
      - "80"
    networks:
      - gcp_network